import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm', 'cjs'],
  dts: true,
  sourcemap: true,
  // Monorepo dev: `tsup --watch` with `clean: true` wipes `dist`, deleting `dist/styles.css`
  // (generated by Tailwind). Storybook imports `@pacer-ui/react/styles.css` → `dist/styles.css`.
  // Keep `dist` intact to avoid 404s / preview.ts import failures while watching.
  clean: false,
  external: ['react', 'react-dom'],
  treeshake: true,
  splitting: false,
  minify: false,
});
